# syntax = docker/dockerfile:1.2
FROM php:7.4-apache
#Install PHP extensions
RUN docker-php-ext-install mysqli
COPY --chown=www-data:www-data ./web/ /var/www/html
RUN --mount=type=secret,id=db_env,dst=/etc/secrets/db_env
RUN . /etc/secrets/db_env
EXPOSE 80
